apiVersion: v1
kind: Pod
metadata:
  name: pod-without-annotation
spec:
  containers:
    - image: debian:buster-slim
      imagePullPolicy: IfNotPresent
      name: sleeper
      command:
      - sleep
      args:
      - "infinity"
