---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "pod-defaulter.fullname" . }}-get-config
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
