apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pod-defaulter.fullname" . }}-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "pod-defaulter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "pod-defaulter.fullname" . }}-get-config
  apiGroup: rbac.authorization.k8s.io